src/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('schemas/', include('schemas.api.urls')),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('schemas/', include('schemas.urls')),
    path('api/', include('api.urls')),
]

src/schemas/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:pk>/', views.generate_csv_data, name='generate-schema'),
]

src/schemas/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('new/', views.SchemaCreateView.as_view(), name='new'),
    path('<int:pk>/', views.SchemaDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.SchemaUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.SchemaDeleteView.as_view(), name='delete'),
    path('', views.SchemaListView.as_view(), name='list'),
    path('dataset/<int:pk>/download/', views.download_dataset, name='download'),
]

app_name = 'schemas'

src/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('logout/', views.LogoutPageView.as_view(), name='logout'),
]

app_name = 'auth'

src/schemas/models.py
from django.db import models
from django.urls import reverse

from .utils import generate_fake_data, generate_csv, get_random_name


class Schema(models.Model):
    """
    Model representing a schema.
    """

    name = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('schemas:detail', kwargs={'pk': self.pk})
    
    def delete(self, *args, **kwargs):
        for dataset in self.datasets.all():
            dataset.delete()
        super().delete(*args, **kwargs)


class Column(models.Model):
    """
    Model representing columns of a schema.
    """

    DATATYPE_CHOICES = (
        ('name', 'Full name'),
        ('job', 'Job'),
        ('email', 'Email'),
        ('phone', 'Phone number'),
        ('date', 'Date'),
    )

    name = models.CharField(max_length=50)
    datatype = models.CharField(max_length=5, choices=DATATYPE_CHOICES)
    order = models.IntegerField()

    schema = models.ForeignKey(Schema, on_delete=models.CASCADE, related_name='columns')

    def generate_fake_value(self):
        return generate_fake_data(self.datatype)

    class Meta:
        ordering = ('order',)


class DataSet(models.Model):
    """
    Model representing dataset.
    """

    created_at = models.DateTimeField(auto_now_add=True)
    csv_file = models.FileField(null=True)

    schema = models.ForeignKey(Schema, on_delete=models.CASCADE, related_name='datasets')

    def generate(self, total: int):
        csv_file = generate_csv(self, total)
        csv_name = get_random_name(prefix='datasets/')
        self.csv_file.save(csv_name, csv_file)

    def delete(self, *args, **kwargs):
        self.csv_file.delete(save=False)
        super().delete(*args, **kwargs)

src/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    Custom user to simplify further changes.
    """
    pass

src/schemas/forms.py
from extra_views import InlineFormSetFactory

from .models import Column


class ColumnInline(InlineFormSetFactory):
    model = Column
    fields = ('name', 'datatype', 'order',)
    factory_kwargs = {'extra': 1}

src/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import User


class CustomUserCreationForm(UserCreationForm):
    """
    Custom user creation form used in the admin panel.
    """

    class Meta:
        model = User
        fields = ('username', 'password',)


class CustomUserChangeForm(UserChangeForm):
    """
    Custom user change form used in the admin panel.
    """

    class Meta:
        model = User
        fields = ('username',)

src/schemas/api/views.py
import json

from django.http import HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse

from ..models import Schema, DataSet


def generate_csv_data(request: HttpRequest, pk: int):
    """
    API endpoint to generate csv dataset based on existing schema.
    """
    
    if request.method == 'POST':
        schema = get_object_or_404(Schema, pk=pk)
        dataset = DataSet.objects.create(schema=schema)

        json_data = json.loads(request.body)
        total = int(json_data.get('total', 10))

        dataset.generate(total)
        dataset.save()

        download_link = reverse('schemas:download', kwargs={'pk': dataset.pk})

        return JsonResponse({'download_link': download_link})

    return JsonResponse({}, status=405)

src/schemas/views.py
from django.http import HttpRequest, FileResponse
from django.views.generic import DetailView, ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy

from extra_views import NamedFormsetsMixin, CreateWithInlinesView, UpdateWithInlinesView

from .forms import ColumnInline
from .models import Schema, DataSet
from .mixins import SchemaFormMixin


class SchemaCreateView(LoginRequiredMixin, SchemaFormMixin, 
                       NamedFormsetsMixin, CreateWithInlinesView):
    """
    Create new schema.
    """

    model = Schema
    inlines = (ColumnInline,)
    inlines_names = ('columns',)
    fields = ('name',)
    template_name = 'schema_form.html'
    page_header = 'New schema'
    page_button = 'Create'


class SchemaUpdateView(LoginRequiredMixin, SchemaFormMixin, 
                       NamedFormsetsMixin, UpdateWithInlinesView):
    """
    Update an existing schema.
    """

    model = Schema
    inlines = (ColumnInline,)
    inlines_names = ('columns',)
    fields = ('name',)
    template_name = 'schema_form.html'
    page_button = 'Save'

    @property
    def page_header(self):
        return self.get_object().name


class SchemaDetailView(LoginRequiredMixin, DetailView):
    """
    Display details of a schema.
    """

    model = Schema
    template_name = 'schema_detail.html'


class SchemaListView(LoginRequiredMixin, ListView):
    """
    List all schemas.
    """

    model = Schema
    template_name = 'schema_list.html'


class SchemaDeleteView(LoginRequiredMixin, DeleteView):
    """
    Delete an existing schema.
    """

    model = Schema
    template_name = 'schema_delete.html'
    success_url = reverse_lazy('schemas:list')


@login_required
def download_dataset(request: HttpRequest, pk: int):
    """
    Download an existing csv dataset.
    """

    dataset = get_object_or_404(DataSet, pk=pk)
    csv_file = dataset.csv_file.file
    return FileResponse(csv_file, as_attachment=True)

src/users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin


class LoginPageView(LoginView):
    """
    View for displaying the login page.
    """
    pass


class LogoutPageView(LoginRequiredMixin, LogoutView):
    """
    View for logging out the user and redirecting to the home page.
    """
    pass

src/templates/base.html
{% load static %}

<!doctype html>
<html>

<head>
  <title>FakeCSV</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'index.css' %}">
</head>

<body>
  <div class="container">
    {% if user.is_authenticated %}
    {% include 'components/_navbar.html' %}
    {% endif %}
    {% include 'components/_flash.html' %}
    <div class="content">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  {% block javascript %}
  {% endblock javascript %}
</body>

</html>

src/templates/components/_columns_form.html
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

<script>
  const newFormHTML = `
    <div class="row">
      {% for field in columns.empty_form %}
        <div class="col-md-3">
          {{ field|as_crispy_field }}
        </div>
      {% endfor %}
    </div>
  `;
</script>

src/templates/components/_flash.html
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

src/templates/components/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">FakeCSV</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'schemas:list' %}">Schemas</a>
        </li>
      </ul>
    </div>
    Hello, {{ user.username }}&nbsp;&nbsp;
    <a class="nav-link active" href="{% url 'auth:logout' %}">Logout</a>
  </div>
</nav>

src/templates/schema_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <div class="alert alert-danger" role="alert">
    Are you sure you want to delete {{ schema.name }}?
  </div>
  <button type="submit" class="btn btn-danger">Confirm</button>
</form>
{% endblock content %}

src/templates/schema_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-3">
    <h3>{{ schema.name }} schema</h3>
  </div>
  <div class="col-md-4" style="margin-top: 5px;">
    <a href="{% url 'schemas:edit' pk=schema.pk %}">Edit schema</a>
  </div>
</div>
<div class="row">
  <div class="col-md-9">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Column name</th>
          <th scope="col">Column type</th>
        </tr>
      </thead>
      <tbody>
        {% for column in schema.columns.all %}
        <tr>
          <th scope="row">{{ column.order }}</th>
          <td>{{ column.name }}</td>
          <td>{{ column.datatype }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<div id="generate-page">
  <div class="row">
    <div class="col-md-6">
      <h3>Data sets</h3>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-4">
          <div class="d-flex justify-content-end">
            Rows:
          </div>
        </div>
        <div class="col-md-4">
          <input type="text" id="total" class="form-control" />
        </div>
        <div class="col-md-4">
          <button type="button" id="add-button" class="btn btn-success">
            Generate data
          </button>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Created</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody id="dataset-list">
          <div id="dataset-list2">
            {% for dataset in schema.datasets.all %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ dataset.created_at|date:"Y-m-d" }}</td>
                <td>
                  {% if dataset.csv_file.url %}
                    <span class="badge text-bg-success">Ready</span>
                  {% else %}
                    <span class="badge text-bg-secondary">Processing</span>
                  {% endif %}
                </td>
                <td>
                  {% if dataset.csv_file.url %}
                    <a href="{% url 'schemas:download' pk=dataset.pk %}">Download</a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </div>
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock content %}

{% block javascript %}
  <script type="module">
    import Cookies from 'https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/+esm';

    const schemaId = `{{ schema.pk }}`;
    const csrf_token = Cookies.get('csrftoken');
    const total = document.getElementById('total');
    const addButton = document.getElementById('add-button');
    const datasetList = document.getElementById('dataset-list');

    const createDataset = () => {
      const newDataset = document.createElement('tr');
      const th = document.createElement('th');
      th.innerHTML = datasetList.childElementCount + 1;
      th.setAttribute('scope', 'row');

      const createdAt = document.createElement('td');
      createdAt.innerHTML = new Date().toISOString().slice(0, 10);

      const status = document.createElement('td');
      status.innerHTML = '<span class="badge text-bg-secondary">Processing</span>';

      const action = document.createElement('td');

      newDataset.appendChild(th);
      newDataset.appendChild(createdAt);
      newDataset.appendChild(status);
      newDataset.appendChild(action);

      return [newDataset, action, status];
    }

    const onClick = async (ev) => {
      ev.preventDefault();
      if(total.value) {
        const [newDataset, action, status] = createDataset();
        datasetList.appendChild(newDataset);
        let totalRows = total.value;
        total.value = '';

        const response = await fetch('/api/schemas/' + schemaId + '/', {
          method: 'POST',
          body: JSON.stringify({total: totalRows}),
          credentials: 'same-origin',
          headers: {
            'X-CSRFToken': csrf_token
          }
        });

        if(response.ok) {
          const data = await response.json();
          status.innerHTML = '<span class="badge text-bg-success">Ready</span>';
          action.innerHTML = `<a href="${data.download_link}">Download</a>`;
        }
      }
    };

    addButton.addEventListener('click', (ev) => {
      onClick(ev);
    });

  </script>
{% endblock javascript %}

src/templates/schema_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block content %}
<h3>{{ schema.name }}</h3>
<div class="schema-form">
  <form method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-8">
        {{ schema_form|crispy }}
      </div>
      <div class="col-md-4">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </div>
    <h3>Schema columns</h3>
    {{ column_formset.management_form }}
    <div id="column-forms">
      {% for form in column_formset.forms %}
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            {% for field in form %}
            <div class="col-md-3">
              {{ field|as_crispy_field }}
            </div>
            {% endfor %}
          </div>
          <hr>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="schema-form-footer">
      <div class="card">
        <div class="card-body">
          <button class="btn btn-primary" type="button" onclick="addColumn()">
            Add column
          </button>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock content %}

{% block javascript %}
<script>
  let columnForms = document.getElementById('column-forms');
  let totalForms = document.getElementById('id_columns-TOTAL_FORMS');

  const addColumn = () => {
    const newFormHTML = `
    <div class="row">
        <div class="col-md-12">
          <div class="row">
            {% for field in column_formset.empty_form %}
            <div class="col-md-3">
              {{ field|as_crispy_field }}
            </div>
            {% endfor %}
          </div>
        </div>
        <hr>
      </div>
    `;

    const newForm = document.createElement('div');
    newForm.innerHTML = newFormHTML.replaceAll('__prefix__', totalForms.value);

    columnForms.appendChild(newForm);
    totalForms.value = parseInt(totalForms.value) + 1;
  };
</script>
{% endblock javascript %}

src/templates/schema_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block content %}
  <h3>{{ page_header }}</h3>
  <form method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-8">
        {{ form|crispy }}
      </div>
      <div class="col-md-4">
        <button type="submit" class="btn btn-primary">{{ page_button }}</button>
      </div>
    </div>
    <h4>Schema columns</h4>
    {{ columns.management_form }}
    <div id="columns-forms">
      {% for form in columns %}
        <div class="row">
          {% for field in form %}
            <div class="col-md-3">
              {{ field|as_crispy_field }}
            </div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
    <div class="row mt-3">
      <div class="card">
        <div class="card-body">
          <button class="btn btn-primary" type="button" onclick="addColumn()">
            Add column
          </button>
        </div>
      </div>
    </div>
  </form>
{% endblock content %}

{% block javascript %}
  {% include 'components/_columns_form.html' %}
  <script>
    let columnForms = document.getElementById('columns-forms');
    let totalForms = document.getElementById('id_columns-TOTAL_FORMS');

    const addColumn = () => {
      const newForm = document.createElement('div');
      newForm.innerHTML = newFormHTML.replaceAll('__prefix__', totalForms.value);

      columnForms.appendChild(newForm);
      totalForms.value = parseInt(totalForms.value) + 1;
    };
  </script>
{% endblock javascript %}

src/templates/schema_list.html
{% extends 'base.html' %}

{% block content %}
<div class="schema-list">
  <div class="row">
    <div class="col-md-6">
      <h3>Data schemas</h3>
    </div>
    <div class="col-md-2">
      <a href="{% url 'schemas:new' %}" class="btn btn-success">New schema</a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="schemas-table">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for schema in schema_list %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td><a href="{% url 'schemas:detail' pk=schema.pk %}">{{ schema.name }}</a></td>
              <td>
                <a href="{% url 'schemas:edit' pk=schema.pk %}" class="link-primary">Edit schema</a>
                <a href="{% url 'schemas:delete' pk=schema.pk %}" class="link-danger" style="padding-left: 10px;">Delete</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

src/templates/schema_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block content %}
<h3>{{ schema.name }}</h3>
<div class="schema-form">
  <form method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-8">
        {{ schema_form|crispy }}
      </div>
      <div class="col-md-4">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </div>
    <h3>Schema columns</h3>
    {{ column_formset.management_form }}
    <div id="column-forms">
      {% for form in column_formset.forms %}
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            {% for field in form %}
            <div class="col-md-3">
              {{ field|as_crispy_field }}
            </div>
            {% endfor %}
          </div>
          <hr>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="schema-form-footer">
      <div class="card">
        <div class="card-body">
          <button class="btn btn-primary" type="button" onclick="addColumn()">
            Add column
          </button>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock content %}

{% block javascript %}
<script>
  let columnForms = document.getElementById('column-forms');
  let totalForms = document.getElementById('id_columns-TOTAL_FORMS');

  const addColumn = () => {
    const newFormHTML = `
    <div class="row">
        <div class="col-md-12">
          <div class="row">
            {% for field in column_formset.empty_form %}
            <div class="col-md-3">
              {{ field|as_crispy_field }}
            </div>
            {% endfor %}
          </div>
        </div>
        <hr>
      </div>
    `;

    const newForm = document.createElement('div');
    newForm.innerHTML = newFormHTML.replaceAll('__prefix__', totalForms.value);

    columnForms.appendChild(newForm);
    totalForms.value = parseInt(totalForms.value) + 1;
  };
</script>
{% endblock javascript %}